Refactor to compress to tar.gz before uploading

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -1,29 +1,23 @@
 #!/bin/bash
-# shellcheck disable=SC2001
 set -euo pipefail
+DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
 
-if [[ "${BUILDKITE_PLUGIN_CACHE_DEBUG:-false}" =~ (true|on|1) ]] ; then
-  set -x
-fi
+# shellcheck source=lib/shared.bash
+. "$DIR/../lib/shared.bash"
+cache_key=$(get_cache_key)
 
-if [[ -n "${BUILDKITE_PLUGIN_CACHE_CACHE_KEY:-}" ]] ; then
+# Set an env var to include the cache key
+# This means we can skip re-uploading the same cache in the post_command
+function mark_restored() {
+  echo "Successfully restored $1"
+  export BUILDKITE_PLUGIN_CACHE_RESTORED=${BUILDKITE_PLUGIN_CACHE_RESTORED:-}:$1:
+}
 
-  cache_key_prefix=$(echo "$BUILDKITE_PLUGIN_CACHE_CACHE_KEY" | sed -e 's/{.*//')
-  template_value=$(echo "$BUILDKITE_PLUGIN_CACHE_CACHE_KEY" | sed -e 's/^[^\{{]*[^A-Za-z]*//' -e 's/.}}.*$//' | tr -d \' | tr -d \")
+echo "Restoring cache $cache_key"
 
-  if [[ $template_value == *"checksum"* ]]; then
-    checksum_argument=$(echo "$template_value" | sed -e 's/checksum*//')
-    function=${template_value/"checksum"/"shasum"}
-    result=$($function | tr -d "$checksum_argument")
-    cache_key="$cache_key_prefix$result"
-  else
-    cache_key=$BUILDKITE_PLUGIN_CACHE_CACHE_KEY
-  fi
-
-  echo ":aws: :amazon-s3: sync ${cache_key}"
-  
-  bucket="${BUILDKITE_PLUGIN_CACHE_S3_BUCKET_NAME}/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}/${cache_key}"
-  
-  aws s3 sync "s3://${bucket}/" . --profile="${BUILDKITE_PLUGIN_CACHE_S3_PROFILE}"
-    
-fi
+bucket="${BUILDKITE_PLUGIN_CACHE_S3_BUCKET_NAME}/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}/$cache_key"
+tmpdir=$(mktemp -d)
+# Set env var if we loaded the cache so we can skip reuploading it
+aws s3 cp "s3://${bucket}/cache.tar.gz" "$tmpdir/" && mark_restored "$cache_key" || echo "Cache not found"
+tar -xzf "$tmpdir/cache.tar.gz"
+rm -rf "$tmpdir"
